export const ErrorCodes = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WITHDRAWAL_NOT_FOUND: "WITHDRAWAL_NOT_FOUND",
  MISSING_IDEMPOTENCY_KEY: "MISSING_IDEMPOTENCY_KEY",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
